spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    initialize-schema: always
    job:
      enabled: false

kafka:
  topics:
    error: "dead-letter"
    result: "worker-launcher"
    launch: "worker-launcher"

aurora:
  datasource:
    url: jdbc:mysql://localhost:3306/schema_db
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver

server:
  port: 8090
