//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 01:14:49 PM EEST 
//


package com.adidas.product.worker.olapic.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="model-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="division-code" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="division" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="display-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="short-description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bullets"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="bullet" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="online" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="online-from" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="online-to" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="category-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="secondary-categories"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="collections"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="collection" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="technologies"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="technology" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="functions"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="function" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sub-gender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sports"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sport-sub" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sport-sub-sub" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="product-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="product-category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="product-filters"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="product-filter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="review"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="customizable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="exclusive" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="search-color" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="partner" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="product-line-style" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="best-for" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="surface" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="foot-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="personalization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="do-not-recommend" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="outlet" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="size-range" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="price"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="district" maxOccurs="9" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="current-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                             &lt;element name="original-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="membersonly-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="cost-price" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="new" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sale" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="discount-amount" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="links-from"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="links-to"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="product" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *                   &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="search-size" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="preorder-backorder-handling" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="preorder-backorder-allocation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="in-stock-date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="previewTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="coming-soon" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Promotion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Flashproduct" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelId",
    "divisionCode",
    "division",
    "displayName",
    "shortDescription",
    "bullets",
    "online",
    "onlineFrom",
    "onlineTo",
    "categoryId",
    "secondaryCategories",
    "collections",
    "technologies",
    "functions",
    "gender",
    "subGender",
    "sports",
    "sportSub",
    "sportSubSub",
    "productType",
    "productCategory",
    "productFilters",
    "type",
    "review",
    "customizable",
    "exclusive",
    "searchColor",
    "color",
    "image",
    "age",
    "partner",
    "productLineStyle",
    "bestFor",
    "surface",
    "footType",
    "activity",
    "frequency",
    "keywords",
    "personalization",
    "doNotRecommend",
    "outlet",
    "stock",
    "sizeRange",
    "price",
    "_new",
    "sale",
    "discountAmount",
    "linksFrom",
    "linksTo",
    "product",
    "previewTo",
    "comingSoon",
    "promotion",
    "flashproduct"
})
@XmlRootElement(name = "article")
public class Article {

    @XmlElement(name = "model-id", required = true)
    protected String modelId;
    @XmlElement(name = "division-code")
    protected byte divisionCode;
    @XmlElement(required = true)
    protected String division;
    @XmlElement(name = "display-name", required = true)
    protected String displayName;
    @XmlElement(name = "short-description", required = true)
    protected String shortDescription;
    @XmlElement(required = true)
    protected Article.Bullets bullets;
    @XmlElement(required = true)
    protected String online;
    @XmlElement(name = "online-from", required = true)
    protected String onlineFrom;
    @XmlElement(name = "online-to", required = true)
    protected String onlineTo;
    @XmlElement(name = "category-id", required = true)
    protected String categoryId;
    @XmlElement(name = "secondary-categories", required = true)
    protected Article.SecondaryCategories secondaryCategories;
    @XmlElement(required = true)
    protected Article.Collections collections;
    @XmlElement(required = true)
    protected Article.Technologies technologies;
    @XmlElement(required = true)
    protected Article.Functions functions;
    @XmlElement(required = true)
    protected String gender;
    @XmlElement(name = "sub-gender", required = true)
    protected String subGender;
    @XmlElement(required = true)
    protected Article.Sports sports;
    @XmlElement(name = "sport-sub", required = true)
    protected String sportSub;
    @XmlElement(name = "sport-sub-sub", required = true)
    protected String sportSubSub;
    @XmlElement(name = "product-type", required = true)
    protected String productType;
    @XmlElement(name = "product-category", required = true)
    protected String productCategory;
    @XmlElement(name = "product-filters", required = true)
    protected Article.ProductFilters productFilters;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected Article.Review review;
    @XmlElement(required = true)
    protected String customizable;
    @XmlElement(required = true)
    protected String exclusive;
    @XmlElement(name = "search-color", required = true)
    protected String searchColor;
    @XmlElement(required = true)
    protected String color;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String image;
    @XmlElement(required = true)
    protected String age;
    @XmlElement(required = true)
    protected String partner;
    @XmlElement(name = "product-line-style", required = true)
    protected String productLineStyle;
    @XmlElement(name = "best-for", required = true)
    protected String bestFor;
    @XmlElement(required = true)
    protected String surface;
    @XmlElement(name = "foot-type", required = true)
    protected String footType;
    @XmlElement(required = true)
    protected String activity;
    @XmlElement(required = true)
    protected String frequency;
    @XmlElement(required = true)
    protected String keywords;
    @XmlElement(required = true)
    protected String personalization;
    @XmlElement(name = "do-not-recommend", required = true)
    protected String doNotRecommend;
    @XmlElement(required = true)
    protected String outlet;
    protected byte stock;
    @XmlElement(name = "size-range")
    protected byte sizeRange;
    @XmlElement(required = true)
    protected Article.Price price;
    @XmlElement(name = "new", required = true)
    protected String _new;
    @XmlElement(required = true)
    protected String sale;
    @XmlElement(name = "discount-amount")
    protected byte discountAmount;
    @XmlElement(name = "links-from", required = true)
    protected Article.LinksFrom linksFrom;
    @XmlElement(name = "links-to", required = true)
    protected Article.LinksTo linksTo;
    protected List<Article.Product> product;
    @XmlElement(required = true)
    protected String previewTo;
    @XmlElement(name = "coming-soon", required = true)
    protected String comingSoon;
    @XmlElement(name = "Promotion", required = true)
    protected String promotion;
    @XmlElement(name = "Flashproduct", required = true)
    protected String flashproduct;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the modelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * Sets the value of the modelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelId(String value) {
        this.modelId = value;
    }

    /**
     * Gets the value of the divisionCode property.
     * 
     */
    public byte getDivisionCode() {
        return divisionCode;
    }

    /**
     * Sets the value of the divisionCode property.
     * 
     */
    public void setDivisionCode(byte value) {
        this.divisionCode = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the bullets property.
     * 
     * @return
     *     possible object is
     *     {@link Article.Bullets }
     *     
     */
    public Article.Bullets getBullets() {
        return bullets;
    }

    /**
     * Sets the value of the bullets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.Bullets }
     *     
     */
    public void setBullets(Article.Bullets value) {
        this.bullets = value;
    }

    /**
     * Gets the value of the online property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnline() {
        return online;
    }

    /**
     * Sets the value of the online property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnline(String value) {
        this.online = value;
    }

    /**
     * Gets the value of the onlineFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlineFrom() {
        return onlineFrom;
    }

    /**
     * Sets the value of the onlineFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlineFrom(String value) {
        this.onlineFrom = value;
    }

    /**
     * Gets the value of the onlineTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlineTo() {
        return onlineTo;
    }

    /**
     * Sets the value of the onlineTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlineTo(String value) {
        this.onlineTo = value;
    }

    /**
     * Gets the value of the categoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * Sets the value of the categoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryId(String value) {
        this.categoryId = value;
    }

    /**
     * Gets the value of the secondaryCategories property.
     * 
     * @return
     *     possible object is
     *     {@link Article.SecondaryCategories }
     *     
     */
    public Article.SecondaryCategories getSecondaryCategories() {
        return secondaryCategories;
    }

    /**
     * Sets the value of the secondaryCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.SecondaryCategories }
     *     
     */
    public void setSecondaryCategories(Article.SecondaryCategories value) {
        this.secondaryCategories = value;
    }

    /**
     * Gets the value of the collections property.
     * 
     * @return
     *     possible object is
     *     {@link Article.Collections }
     *     
     */
    public Article.Collections getCollections() {
        return collections;
    }

    /**
     * Sets the value of the collections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.Collections }
     *     
     */
    public void setCollections(Article.Collections value) {
        this.collections = value;
    }

    /**
     * Gets the value of the technologies property.
     * 
     * @return
     *     possible object is
     *     {@link Article.Technologies }
     *     
     */
    public Article.Technologies getTechnologies() {
        return technologies;
    }

    /**
     * Sets the value of the technologies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.Technologies }
     *     
     */
    public void setTechnologies(Article.Technologies value) {
        this.technologies = value;
    }

    /**
     * Gets the value of the functions property.
     * 
     * @return
     *     possible object is
     *     {@link Article.Functions }
     *     
     */
    public Article.Functions getFunctions() {
        return functions;
    }

    /**
     * Sets the value of the functions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.Functions }
     *     
     */
    public void setFunctions(Article.Functions value) {
        this.functions = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the subGender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubGender() {
        return subGender;
    }

    /**
     * Sets the value of the subGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubGender(String value) {
        this.subGender = value;
    }

    /**
     * Gets the value of the sports property.
     * 
     * @return
     *     possible object is
     *     {@link Article.Sports }
     *     
     */
    public Article.Sports getSports() {
        return sports;
    }

    /**
     * Sets the value of the sports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.Sports }
     *     
     */
    public void setSports(Article.Sports value) {
        this.sports = value;
    }

    /**
     * Gets the value of the sportSub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSportSub() {
        return sportSub;
    }

    /**
     * Sets the value of the sportSub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSportSub(String value) {
        this.sportSub = value;
    }

    /**
     * Gets the value of the sportSubSub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSportSubSub() {
        return sportSubSub;
    }

    /**
     * Sets the value of the sportSubSub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSportSubSub(String value) {
        this.sportSubSub = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCategory(String value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the productFilters property.
     * 
     * @return
     *     possible object is
     *     {@link Article.ProductFilters }
     *     
     */
    public Article.ProductFilters getProductFilters() {
        return productFilters;
    }

    /**
     * Sets the value of the productFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.ProductFilters }
     *     
     */
    public void setProductFilters(Article.ProductFilters value) {
        this.productFilters = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the review property.
     * 
     * @return
     *     possible object is
     *     {@link Article.Review }
     *     
     */
    public Article.Review getReview() {
        return review;
    }

    /**
     * Sets the value of the review property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.Review }
     *     
     */
    public void setReview(Article.Review value) {
        this.review = value;
    }

    /**
     * Gets the value of the customizable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomizable() {
        return customizable;
    }

    /**
     * Sets the value of the customizable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomizable(String value) {
        this.customizable = value;
    }

    /**
     * Gets the value of the exclusive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExclusive() {
        return exclusive;
    }

    /**
     * Sets the value of the exclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExclusive(String value) {
        this.exclusive = value;
    }

    /**
     * Gets the value of the searchColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchColor() {
        return searchColor;
    }

    /**
     * Sets the value of the searchColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchColor(String value) {
        this.searchColor = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the partner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartner() {
        return partner;
    }

    /**
     * Sets the value of the partner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartner(String value) {
        this.partner = value;
    }

    /**
     * Gets the value of the productLineStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductLineStyle() {
        return productLineStyle;
    }

    /**
     * Sets the value of the productLineStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductLineStyle(String value) {
        this.productLineStyle = value;
    }

    /**
     * Gets the value of the bestFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBestFor() {
        return bestFor;
    }

    /**
     * Sets the value of the bestFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBestFor(String value) {
        this.bestFor = value;
    }

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurface() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurface(String value) {
        this.surface = value;
    }

    /**
     * Gets the value of the footType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFootType() {
        return footType;
    }

    /**
     * Sets the value of the footType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFootType(String value) {
        this.footType = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivity(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeywords(String value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the personalization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalization() {
        return personalization;
    }

    /**
     * Sets the value of the personalization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalization(String value) {
        this.personalization = value;
    }

    /**
     * Gets the value of the doNotRecommend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoNotRecommend() {
        return doNotRecommend;
    }

    /**
     * Sets the value of the doNotRecommend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoNotRecommend(String value) {
        this.doNotRecommend = value;
    }

    /**
     * Gets the value of the outlet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutlet() {
        return outlet;
    }

    /**
     * Sets the value of the outlet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutlet(String value) {
        this.outlet = value;
    }

    /**
     * Gets the value of the stock property.
     * 
     */
    public byte getStock() {
        return stock;
    }

    /**
     * Sets the value of the stock property.
     * 
     */
    public void setStock(byte value) {
        this.stock = value;
    }

    /**
     * Gets the value of the sizeRange property.
     * 
     */
    public byte getSizeRange() {
        return sizeRange;
    }

    /**
     * Sets the value of the sizeRange property.
     * 
     */
    public void setSizeRange(byte value) {
        this.sizeRange = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Article.Price }
     *     
     */
    public Article.Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.Price }
     *     
     */
    public void setPrice(Article.Price value) {
        this.price = value;
    }

    /**
     * Gets the value of the new property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNew() {
        return _new;
    }

    /**
     * Sets the value of the new property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNew(String value) {
        this._new = value;
    }

    /**
     * Gets the value of the sale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSale() {
        return sale;
    }

    /**
     * Sets the value of the sale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSale(String value) {
        this.sale = value;
    }

    /**
     * Gets the value of the discountAmount property.
     * 
     */
    public byte getDiscountAmount() {
        return discountAmount;
    }

    /**
     * Sets the value of the discountAmount property.
     * 
     */
    public void setDiscountAmount(byte value) {
        this.discountAmount = value;
    }

    /**
     * Gets the value of the linksFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Article.LinksFrom }
     *     
     */
    public Article.LinksFrom getLinksFrom() {
        return linksFrom;
    }

    /**
     * Sets the value of the linksFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.LinksFrom }
     *     
     */
    public void setLinksFrom(Article.LinksFrom value) {
        this.linksFrom = value;
    }

    /**
     * Gets the value of the linksTo property.
     * 
     * @return
     *     possible object is
     *     {@link Article.LinksTo }
     *     
     */
    public Article.LinksTo getLinksTo() {
        return linksTo;
    }

    /**
     * Sets the value of the linksTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article.LinksTo }
     *     
     */
    public void setLinksTo(Article.LinksTo value) {
        this.linksTo = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Article.Product }
     * 
     * 
     */
    public List<Article.Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Article.Product>();
        }
        return this.product;
    }

    /**
     * Gets the value of the previewTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviewTo() {
        return previewTo;
    }

    /**
     * Sets the value of the previewTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviewTo(String value) {
        this.previewTo = value;
    }

    /**
     * Gets the value of the comingSoon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComingSoon() {
        return comingSoon;
    }

    /**
     * Sets the value of the comingSoon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComingSoon(String value) {
        this.comingSoon = value;
    }

    /**
     * Gets the value of the promotion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotion() {
        return promotion;
    }

    /**
     * Sets the value of the promotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotion(String value) {
        this.promotion = value;
    }

    /**
     * Gets the value of the flashproduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlashproduct() {
        return flashproduct;
    }

    /**
     * Sets the value of the flashproduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlashproduct(String value) {
        this.flashproduct = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="bullet" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bullet"
    })
    public static class Bullets {

        protected List<String> bullet;

        /**
         * Gets the value of the bullet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bullet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBullet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getBullet() {
            if (bullet == null) {
                bullet = new ArrayList<String>();
            }
            return this.bullet;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="collection" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "collection"
    })
    public static class Collections {

        protected List<String> collection;

        /**
         * Gets the value of the collection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the collection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCollection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCollection() {
            if (collection == null) {
                collection = new ArrayList<String>();
            }
            return this.collection;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="function" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "function"
    })
    public static class Functions {

        protected List<String> function;

        /**
         * Gets the value of the function property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the function property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFunction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getFunction() {
            if (function == null) {
                function = new ArrayList<String>();
            }
            return this.function;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "link"
    })
    public static class LinksFrom {

        protected List<String> link;

        /**
         * Gets the value of the link property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the link property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLink().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLink() {
            if (link == null) {
                link = new ArrayList<String>();
            }
            return this.link;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "link"
    })
    public static class LinksTo {

        protected List<String> link;

        /**
         * Gets the value of the link property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the link property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLink().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLink() {
            if (link == null) {
                link = new ArrayList<String>();
            }
            return this.link;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="district" maxOccurs="9" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="current-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                   &lt;element name="original-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="membersonly-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="cost-price" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currency",
        "district",
        "membersonlyPrice",
        "costPrice"
    })
    public static class Price {

        @XmlElement(required = true)
        protected String currency;
        protected List<Article.Price.District> district;
        @XmlElement(name = "membersonly-price")
        protected float membersonlyPrice;
        @XmlElement(name = "cost-price")
        protected Float costPrice;

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the district property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the district property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDistrict().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Article.Price.District }
         * 
         * 
         */
        public List<Article.Price.District> getDistrict() {
            if (district == null) {
                district = new ArrayList<Article.Price.District>();
            }
            return this.district;
        }

        /**
         * Gets the value of the membersonlyPrice property.
         * 
         */
        public float getMembersonlyPrice() {
            return membersonlyPrice;
        }

        /**
         * Sets the value of the membersonlyPrice property.
         * 
         */
        public void setMembersonlyPrice(float value) {
            this.membersonlyPrice = value;
        }

        /**
         * Gets the value of the costPrice property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getCostPrice() {
            return costPrice;
        }

        /**
         * Sets the value of the costPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setCostPrice(Float value) {
            this.costPrice = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="current-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *         &lt;element name="original-price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "currentPrice",
            "originalPrice"
        })
        public static class District {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(name = "current-price")
            protected float currentPrice;
            @XmlElement(name = "original-price")
            protected float originalPrice;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the currentPrice property.
             * 
             */
            public float getCurrentPrice() {
                return currentPrice;
            }

            /**
             * Sets the value of the currentPrice property.
             * 
             */
            public void setCurrentPrice(float value) {
                this.currentPrice = value;
            }

            /**
             * Gets the value of the originalPrice property.
             * 
             */
            public float getOriginalPrice() {
                return originalPrice;
            }

            /**
             * Sets the value of the originalPrice property.
             * 
             */
            public void setOriginalPrice(float value) {
                this.originalPrice = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
     *         &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="search-size" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="preorder-backorder-handling" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="preorder-backorder-allocation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="in-stock-date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "url",
        "stock",
        "size",
        "searchSize",
        "preorderBackorderHandling",
        "preorderBackorderAllocation",
        "inStockDate"
    })
    public static class Product {

        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String url;
        protected byte stock;
        @XmlElement(required = true)
        protected String size;
        @XmlElement(name = "search-size", required = true)
        protected String searchSize;
        @XmlElement(name = "preorder-backorder-handling", required = true)
        protected String preorderBackorderHandling;
        @XmlElement(name = "preorder-backorder-allocation", required = true)
        protected String preorderBackorderAllocation;
        @XmlElement(name = "in-stock-date", required = true)
        protected String inStockDate;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the stock property.
         * 
         */
        public byte getStock() {
            return stock;
        }

        /**
         * Sets the value of the stock property.
         * 
         */
        public void setStock(byte value) {
            this.stock = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSize(String value) {
            this.size = value;
        }

        /**
         * Gets the value of the searchSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchSize() {
            return searchSize;
        }

        /**
         * Sets the value of the searchSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchSize(String value) {
            this.searchSize = value;
        }

        /**
         * Gets the value of the preorderBackorderHandling property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreorderBackorderHandling() {
            return preorderBackorderHandling;
        }

        /**
         * Sets the value of the preorderBackorderHandling property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreorderBackorderHandling(String value) {
            this.preorderBackorderHandling = value;
        }

        /**
         * Gets the value of the preorderBackorderAllocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreorderBackorderAllocation() {
            return preorderBackorderAllocation;
        }

        /**
         * Sets the value of the preorderBackorderAllocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreorderBackorderAllocation(String value) {
            this.preorderBackorderAllocation = value;
        }

        /**
         * Gets the value of the inStockDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInStockDate() {
            return inStockDate;
        }

        /**
         * Sets the value of the inStockDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInStockDate(String value) {
            this.inStockDate = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="product-filter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productFilter"
    })
    public static class ProductFilters {

        @XmlElement(name = "product-filter", required = true)
        protected String productFilter;

        /**
         * Gets the value of the productFilter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductFilter() {
            return productFilter;
        }

        /**
         * Sets the value of the productFilter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductFilter(String value) {
            this.productFilter = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rating",
        "count"
    })
    public static class Review {

        protected float rating;
        protected byte count;

        /**
         * Gets the value of the rating property.
         * 
         */
        public float getRating() {
            return rating;
        }

        /**
         * Sets the value of the rating property.
         * 
         */
        public void setRating(float value) {
            this.rating = value;
        }

        /**
         * Gets the value of the count property.
         * 
         */
        public byte getCount() {
            return count;
        }

        /**
         * Sets the value of the count property.
         * 
         */
        public void setCount(byte value) {
            this.count = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category"
    })
    public static class SecondaryCategories {

        protected List<String> category;

        /**
         * Gets the value of the category property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the category property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCategory() {
            if (category == null) {
                category = new ArrayList<String>();
            }
            return this.category;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sport"
    })
    public static class Sports {

        protected List<String> sport;

        /**
         * Gets the value of the sport property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sport property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSport() {
            if (sport == null) {
                sport = new ArrayList<String>();
            }
            return this.sport;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="technology" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "technology"
    })
    public static class Technologies {

        protected List<String> technology;

        /**
         * Gets the value of the technology property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the technology property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTechnology().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTechnology() {
            if (technology == null) {
                technology = new ArrayList<String>();
            }
            return this.technology;
        }

    }

}
