//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 01:14:49 PM EEST 
//


package com.adidas.product.worker.olapic.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.adidas.product.worker.olapic.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.adidas.product.worker.olapic.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Article.Price }
     * 
     */
    public Article.Price createArticlePrice() {
        return new Article.Price();
    }

    /**
     * Create an instance of {@link Article.Bullets }
     * 
     */
    public Article.Bullets createArticleBullets() {
        return new Article.Bullets();
    }

    /**
     * Create an instance of {@link Article.SecondaryCategories }
     * 
     */
    public Article.SecondaryCategories createArticleSecondaryCategories() {
        return new Article.SecondaryCategories();
    }

    /**
     * Create an instance of {@link Article.Collections }
     * 
     */
    public Article.Collections createArticleCollections() {
        return new Article.Collections();
    }

    /**
     * Create an instance of {@link Article.Technologies }
     * 
     */
    public Article.Technologies createArticleTechnologies() {
        return new Article.Technologies();
    }

    /**
     * Create an instance of {@link Article.Functions }
     * 
     */
    public Article.Functions createArticleFunctions() {
        return new Article.Functions();
    }

    /**
     * Create an instance of {@link Article.Sports }
     * 
     */
    public Article.Sports createArticleSports() {
        return new Article.Sports();
    }

    /**
     * Create an instance of {@link Article.ProductFilters }
     * 
     */
    public Article.ProductFilters createArticleProductFilters() {
        return new Article.ProductFilters();
    }

    /**
     * Create an instance of {@link Article.Review }
     * 
     */
    public Article.Review createArticleReview() {
        return new Article.Review();
    }

    /**
     * Create an instance of {@link Article.LinksFrom }
     * 
     */
    public Article.LinksFrom createArticleLinksFrom() {
        return new Article.LinksFrom();
    }

    /**
     * Create an instance of {@link Article.LinksTo }
     * 
     */
    public Article.LinksTo createArticleLinksTo() {
        return new Article.LinksTo();
    }

    /**
     * Create an instance of {@link Article.Product }
     * 
     */
    public Article.Product createArticleProduct() {
        return new Article.Product();
    }

    /**
     * Create an instance of {@link Article.Price.District }
     * 
     */
    public Article.Price.District createArticlePriceDistrict() {
        return new Article.Price.District();
    }

}
